### ISSUE TITLE
Incentive to run a node

### ISSUE THREAD

**Issue by ghost** [LiskArchive/lisk-node#10]
I really like to contribute to the Lisk network with nodes to help with transactions and securing the blockchain, but if there is no incentive for me to do so im withholding from my investment. A Lisk reward program would really help.

**Comment by karmacoma** [comment]
@Joo5t This is not correct repository. The Lisk Core is maintained here: https://github.com/LiskHQ/lisk 

In answer to your question, please see: https://docs.lisk.io/v1.1/docs/faq-network#section-how-are-new-lsk-tokens-created-. Thanks.
