### ISSUE TITLE
Fails to build on Archlinux.

### ISSUE THREAD

**Issue by 4fryn** [LiskArchive/lisk-node#7]
* **Version**: v6.10.1-lisk
* **Platform**: Linux 4.11.2
* **Subsystem**: ArchLinux, gcc 7.1.1, python 2.7.13

The following command

    python2 ./configure

Throws

    creating ./icu_config.gypi
    * Using ICU in deps/icu-small
    Using version-specific floating patch tools/icu/patches/58/source/i18n/digitlst.cpp
    creating ./icu_config.gypi
    { 'target_defaults': { 'cflags': [],
                           'default_configuration': 'Release',
                           'defines': [],
                           'include_dirs': [],
                           'libraries': []},
      'variables': { 'asan': 0,
                     'coverage': 'false',
                     'debug_devtools': 'node',
                     'force_dynamic_crt': 0,
                     'gas_version': '2.28',
                     'host_arch': 'x64',
                     'icu_data_file': 'icudt58l.dat',
                     'icu_data_in': '../../deps/icu-small/source/data/in/icudt58l.dat',
                     'icu_endianness': 'l',
                     'icu_gyp_path': 'tools/icu/icu-generic.gyp',
                     'icu_locales': 'en,root',
                     'icu_path': 'deps/icu-small',
                     'icu_small': 'true',
                     'icu_ver_major': '58',
                     'node_byteorder': 'little',
                     'node_enable_d8': 'false',
                     'node_enable_v8_vtunejit': 'false',
                     'node_install_npm': 'true',
                     'node_module_version': 48,
                     'node_no_browser_globals': 'false',
                     'node_prefix': '/usr/local',
                     'node_release_urlbase': '',
                     'node_shared': 'false',
                     'node_shared_cares': 'false',
                     'node_shared_http_parser': 'false',
                     'node_shared_libuv': 'false',
                     'node_shared_openssl': 'false',
                     'node_shared_zlib': 'false',
                     'node_tag': '',
                     'node_use_bundled_v8': 'true',
                     'node_use_dtrace': 'false',
                     'node_use_etw': 'false',
                     'node_use_lttng': 'false',
                     'node_use_openssl': 'true',
                     'node_use_perfctr': 'false',
                     'node_use_v8_platform': 'true',
                     'openssl_fips': '',
                     'openssl_no_asm': 0,
                     'shlib_suffix': 'so.48',
                     'target_arch': 'x64',
                     'uv_parent_path': '/deps/uv/',
                     'uv_use_dtrace': 'false',
                     'v8_enable_gdbjit': 0,
                     'v8_enable_i18n_support': 1,
                     'v8_inspector': 'true',
                     'v8_no_strict_aliasing': 1,
                     'v8_optimized_debug': 0,
                     'v8_random_seed': 0,
                     'v8_use_snapshot': 'true',
                     'want_separate_host_toolset': 0}}
    creating ./config.gypi
    creating ./config.mk
      File "<string>", line 1
        import sys; print sys.byteorder
                            ^
    SyntaxError: invalid syntax
    gyp: Call to 'python -c "import sys; print sys.byteorder"' returned exit status 1 while in /home/lisk/src/lisk-archlinux/lisk-git/src/lisk-node/deps/v8/tools/gyp/v8.gyp. while loading dependencies of /home/lisk/src/lisk-archlinux/lisk-git/src/lisk-node/node.gyp while trying to load /home/lisk/src/lisk-archlinux/lisk-git/src/lisk-node/node.gyp
    Error running GYP

**Comment by Isabello** [comment]
Please try building from this branch:

https://github.com/LiskHQ/lisk-node/tree/v6.10.3-release

This is the tagged release from Node, if the build fails with this branch then its an issue with node and not our customized nodejs.

**Comment by 4fryn** [comment]
@Isabello you are lucky tonight. https://github.com/nodejs/node/issues/2735
